all:
  children:
    k3s_cluster:
      children:
        master:
          hosts:
            rp2:
              ansible_host: 10.0.0.72
        worker:
          hosts:
            rp1: 
              ansible_host: 10.0.0.73